version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7999:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
  db:
    image: "mysql/mysql-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "todo"
    expose:
      - "3306"
